apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"

  - name: CloudWatch
    type: cloudwatch
    uid: cloudwatch
    access: proxy
    editable: true
    jsonData:
      authType: ec2_iam_role
      defaultRegion: eu-west-1

  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger:16686
    editable: true
    jsonData:
      nodeGraph:
        enabled: true
